// Trello Board Actions
export const TRELLO_FETCH_DATA_REQUEST = 'TRELLO_FETCH_DATA_REQUEST';
export const TRELLO_FETCH_DATA_SUCCESS = 'TRELLO_FETCH_DATA_SUCCESS';
export const TRELLO_FETCH_DATA_FAILURE = 'TRELLO_FETCH_DATA_FAILURE';

export const TRELLO_ADD_LIST_REQUEST = 'TRELLO_ADD_LIST_REQUEST';
export const TRELLO_ADD_LIST_SUCCESS = 'TRELLO_ADD_LIST_SUCCESS';
export const TRELLO_ADD_LIST_FAILURE = 'TRELLO_ADD_LIST_FAILURE';

export const TRELLO_DELETE_LIST_REQUEST = 'TRELLO_DELETE_LIST_REQUEST';
export const TRELLO_DELETE_LIST_SUCCESS = 'TRELLO_DELETE_LIST_SUCCESS';
export const TRELLO_DELETE_LIST_FAILURE = 'TRELLO_DELETE_LIST_FAILURE';

export const TRELLO_ADD_CARD_REQUEST = 'TRELLO_ADD_CARD_REQUEST';
export const TRELLO_ADD_CARD_SUCCESS = 'TRELLO_ADD_CARD_SUCCESS';
export const TRELLO_ADD_CARD_FAILURE = 'TRELLO_ADD_CARD_FAILURE';

export const TRELLO_DELETE_CARD_REQUEST = 'TRELLO_DELETE_CARD_REQUEST';
export const TRELLO_DELETE_CARD_SUCCESS = 'TRELLO_DELETE_CARD_SUCCESS';
export const TRELLO_DELETE_CARD_FAILURE = 'TRELLO_DELETE_CARD_FAILURE';

export const TRELLO_UPDATE_CARD_CONTENT = 'TRELLO_UPDATE_CARD_CONTENT';
export const TRELLO_UPDATE_CARD_CONTENT_REQUEST = 'TRELLO_UPDATE_CARD_CONTENT_REQUEST';
export const TRELLO_UPDATE_CARD_CONTENT_SUCCESS = 'TRELLO_UPDATE_CARD_CONTENT_SUCCESS';
export const TRELLO_UPDATE_CARD_CONTENT_FAILURE = 'TRELLO_UPDATE_CARD_CONTENT_FAILURE';

export const TRELLO_DRAG_CARD_REQUEST = 'TRELLO_DRAG_CARD_REQUEST';
export const TRELLO_DRAG_CARD_SUCCESS = 'TRELLO_DRAG_CARD_SUCCESS';
export const TRELLO_DRAG_CARD_FAILURE = 'TRELLO_DRAG_CARD_FAILURE';

// UI State
export const TRELLO_SET_LOADING = 'TRELLO_SET_LOADING';
export const TRELLO_SET_SAVING = 'TRELLO_SET_SAVING';
export const TRELLO_SET_DELETING = 'TRELLO_SET_DELETING';
export const TRELLO_SET_HOVERED_CARD = 'TRELLO_SET_HOVERED_CARD';
export const TRELLO_SET_DRAG_DATA = 'TRELLO_SET_DRAG_DATA';

// Modal states
export const TRELLO_OPEN_CARD_INFO = 'TRELLO_OPEN_CARD_INFO';
export const TRELLO_CLOSE_CARD_INFO = 'TRELLO_CLOSE_CARD_INFO';
export const TRELLO_SHOW_DELETE_LIST_MODAL = 'TRELLO_SHOW_DELETE_LIST_MODAL';
export const TRELLO_HIDE_DELETE_LIST_MODAL = 'TRELLO_HIDE_DELETE_LIST_MODAL';
